### ISSUE TITLE
`pip` install still not working

### ISSUE THREAD

**Issue by dannys4** [MeasureTransport/MParT#326]
```
$ pip install mpart
...
$ python
>>> import mpart as mt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dannys4/mambaforge/envs/tmp/lib/python3.11/site-packages/mpart/__init__.py", line 2, in <module>
    from .pympart import *
ImportError: libnlopt.so.0: cannot open shared object file: No such file or directory
```

**Comment by michael-c-brennan** [comment]
I see similar errors for a few different Python versions. In Python 3.8.15 doing a user install on supercloud:
```
Python 3.8.15 (default, Nov 24 2022, 15:19:38) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpart as mt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gridsan/mbrennan/.local/lib/python3.8/site-packages/mpart/__init__.py", line 2, in <module>
    from .pympart import *
ImportError: libkokkoscore.so.3.7: cannot open shared object file: No such file or directory
```
and in a fresh conda env with Python 3.10.10:
```
Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpart as mt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gridsan/mbrennan/.conda/envs/mpart-pip/lib/python3.10/site-packages/mpart/__init__.py", line 2, in <module>
    from .pympart import *
ImportError: libnlopt.so.0: cannot open shared object file: No such file or directory
```

**Comment by mparno** [comment]
I suspect this is all related to the RPATh of the libraries built
internally by cmake for MParT.    If you set the LD_LIBRARY_PATH to the
folder containing those libraries, does the error go away?

**Comment by mparno** [comment]
@dannys4 Besides the python version, could you give some more insight into your system?  I'm having issues reconstructing this issue.  I've tried fresh conda environments on OSX and the `python:3.11.3-slim` docker image and haven't run into any issues.

**Comment by dannys4** [comment]
So I just recreated this in Linux using Mamba in a fresh environment with python 3.11.3. It looks like this issue is corrected once you investigate `LD_LIBRARY_PATH` and correct it. For some reason, `~/mambaforge/envs/my-env/lib/` (which is where the libraries seem to be located) is not on the library path?

**Comment by dannys4** [comment]
It looks like, in my scenario, `sys.prefix` is equivalent to `~/mambaforge/envs/my-env`. Then, in the `setup.py` file, I believe we should be adding `sys.prefix + '/lib'` as a possible path, since that's where the libraries get added. I'd suggest the docker image already has `sys.prefix + 'lib'` already on the library path. I couldn't tell you why your conda works, but mamba 1.1.0 is based on conda 22.9.0, if that helps/hurts your diagnosis.
